### ISSUE TITLE
Multiple robots

### ISSUE THREAD

**Issue by zeidk** [RobotnikAutomation/rbkairos_sim#15]
Hi,
how to spawn multiple robots in the same environment? I am currently using `roslaunch rbkairos_sim_bringup rbkairos_complete.launch launch_robot_b:=true` and I have both robots in RViz and Gazebo. However, each robot has its own map frame `robot_map` and `robot_b_map`. Is there a way to have one common map frame for both robots? Should I do the remapping myself or is there an easy change that can be made in one of the launch files?

Thank you

**Comment by zeidk** [comment]
I just want to add that I'm using the github repositories and not the Debian ones.

**Comment by alex-arnal** [comment]
Hi,
the simplest way to make the robots share the environment is creating a parent frame that points to the map frame of both robots.

As both robots are using the same map you can just create an static transform like this:

* This will create a parent frame called _world_ for _robot\_map_ that equals in position and orientation. 
```bash
rosrun tf static_transform_publisher 0 0 0 0 0 0 world robot_map 100
```

* With the second static transform you can link the second robot to the TFs tree of the first robot using _world_ as connection
```bash
rosrun tf static_transform_publisher 0 0 0 0 0 0 world robot_b_map 100
```

Once you have both robots connected, you should be capable to see the second robot in the TFs tree representation of the first robot in RVIZ.
![sharing_map](https://user-images.githubusercontent.com/30115565/163113256-cc46e6db-fd67-41da-aeb4-6856565c872f.png)

**Comment by zeidk** [comment]
Awesome! Thank you very much for the fast reply.
Also, is there a more detailed documentation on this package? There are many arguments we can pass to the launch files. Some of these arguments are intuitive while others are not easy to guess.
