### ISSUE TITLE
Impossible to run rbkairos with moveit

### ISSUE THREAD

**Issue by rpl-as-ucl** [RobotnikAutomation/rbkairos_sim#5]
Hello. We try to make rb_kairos run with moveit (ur5) but it is impossible. It appears that the roslaunch rbkairos_sim_bringup rbkairos_complete.launch move_group_robot_a:=true never initializes MoveIt! for the arm. Do you have the same problem?

**Comment by RomanRobotnik** [comment]
The name of the argument was incorrect in the README file. The correct one is **moveit_movegroup_a**.

Thanks for reporting the issue!
