### ISSUE TITLE
Gripper

### ISSUE THREAD

**Issue by armulrich** [RobotnikAutomation/rbkairos_sim#8]
I just successfully launched the sim after switching to the new structure branch and running 

`roslaunch rbkairos_sim_bringup run_simulator.launch`
`roslaunch rbkairos_sim_bringup run_robot.launch`

seperatly, because when running 

`roslaunch rbkairos_sim_bringup rbkairos_complete.launch`

I received a lot of errors and now I only have the pid gain error which I can think I can ignore (please correct me if I am wrong). 

Now I am having trouble adding the egh gripper with the ur,  because I don't know which changes to make to the launch commands/file in order to make that work. 

Afterwards I plan to use it with the rbkairos_common egh moveit.

**Comment by alex-arnal** [comment]
Hi,

Could you show me the errors that you are facing when launching rbkairos_complete.launch? I have tried it and I have the pid gain error and other one related to the teleop_panel, but it is not critical. As you say, you can ignore the pid gain error. By default, with rbkairos_complete.launch a mobile base is launched equipped with an UR5 and no gripper. 

If you want to launch the robot with an EGH Gripper, you will need to add some packages to the workspace:

[egh_gripper_common](https://github.com/RobotnikAutomation/egh_gripper_common)
[roboticsgroup_gazebo_plugins](https://github.com/RobotnikAutomation/roboticsgroup_gazebo_plugins)

In addition, you will need to pass some arguments to the launch file. It should look like this:

```bash
roslaunch rbkairos_sim_bringup rbkairos_complete.launch robot_xacro:=versions/rbkairos_ur5_egh.urdf.xacro launch_gripper_control:=true
```
Here the list of packages in my workspace
- egh_gripper_common  
- fmauch_universal_robot  
- rbkairos_common  
- rbkairos_sim  
- roboticsgroup_gazebo_plugins  
- robotnik_sensors  
- summit_xl_common  
- Universal_Robots_ROS_Driver

I have tested it with Ubuntu 16.04, Kinetic and Gazebo 9.16.0 but it should also work in Ubuntu 18.04, Melodic, etc.

Álex.

**Comment by armulrich** [comment]
Thank you very much for the response Álex

Just for your information I am using:
Melodic  with Ubuntu 18.04

I have checked multiple times and I think I have all the packages installed, but when running 
`roslaunch rbkairos_sim_bringup rbkairos_complete.launch robot_xacro:=versions/rbkairos_ur5_egh.urdf.xacro launch_gripper_control:=true`

It loads the world without the robot and the rviz does not display a robot. In addition to that the terminal messages are:

`
SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot/arm/force_torque_sensor_controller/publish_rate: 125
 * /robot/arm/force_torque_sensor_controller/type: force_torque_sens...
 * /robot/arm/hardware_control_loop/loop_hz: 125
 * /robot/arm/hardware_interface/joints: ['robot_arm_shoul...
 * /robot/arm/joint_state_controller/publish_rate: 125
 * /robot/arm/joint_state_controller/type: joint_state_contr...
 * /robot/arm/pos_traj_controller/action_monitor_rate: 10
 * /robot/arm/pos_traj_controller/constraints/goal_time: 0.6
 * /robot/arm/pos_traj_controller/constraints/robot_arm_elbow_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_elbow_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/robot_arm_shoulder_lift_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_shoulder_lift_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/robot_arm_shoulder_pan_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_shoulder_pan_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_1_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_1_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_2_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_2_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_3_joint/goal: 0.1
 * /robot/arm/pos_traj_controller/constraints/robot_arm_wrist_3_joint/trajectory: 0.2
 * /robot/arm/pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /robot/arm/pos_traj_controller/joints: ['robot_arm_shoul...
 * /robot/arm/pos_traj_controller/state_publish_rate: 125
 * /robot/arm/pos_traj_controller/stop_trajectory_duration: 0.5
 * /robot/arm/pos_traj_controller/type: position_controll...
 * /robot/arm/scaled_pos_traj_controller/action_monitor_rate: 10
 * /robot/arm/scaled_pos_traj_controller/constraints/goal_time: 0.6
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_elbow_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_elbow_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_shoulder_lift_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_shoulder_lift_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_shoulder_pan_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_shoulder_pan_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_1_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_1_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_2_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_2_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_3_joint/goal: 0.1
 * /robot/arm/scaled_pos_traj_controller/constraints/robot_arm_wrist_3_joint/trajectory: 0.2
 * /robot/arm/scaled_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /robot/arm/scaled_pos_traj_controller/joints: ['robot_arm_shoul...
 * /robot/arm/scaled_pos_traj_controller/state_publish_rate: 125
 * /robot/arm/scaled_pos_traj_controller/stop_trajectory_duration: 0.5
 * /robot/arm/scaled_pos_traj_controller/type: position_controll...
 * /robot/arm/speed_scaling_state_controller/publish_rate: 125
 * /robot/arm/speed_scaling_state_controller/type: ur_controllers/Sp...
 * /robot/gripper/gripper_controller/joint: robot_egh_gripper...
 * /robot/gripper/gripper_controller/type: position_controll...
 * /robot/joint_pan_position_controller/joint: robot_front_ptz_c...
 * /robot/joint_pan_position_controller/pid/d: 10.0
 * /robot/joint_pan_position_controller/pid/i: 0.01
 * /robot/joint_pan_position_controller/pid/p: 100.0
 * /robot/joint_pan_position_controller/type: velocity_controll...
 * /robot/joint_read_state_controller/publish_rate: 100.0
 * /robot/joint_read_state_controller/type: joint_state_contr...
 * /robot/joint_tilt_position_controller/joint: robot_front_ptz_c...
 * /robot/joint_tilt_position_controller/pid/d: 10.0
 * /robot/joint_tilt_position_controller/pid/i: 0.01
 * /robot/joint_tilt_position_controller/pid/p: 100.0
 * /robot/joint_tilt_position_controller/type: velocity_controll...
 * /robot/robot_description: <?xml version="1....
 * /robot/robotnik_base_control/angular/z/has_acceleration_limits: True
 * /robot/robotnik_base_control/angular/z/has_velocity_limits: True
 * /robot/robotnik_base_control/angular/z/max_acceleration: 6.0
 * /robot/robotnik_base_control/angular/z/max_velocity: 6.0
 * /robot/robotnik_base_control/base_frame_id: robot_base_footprint
 * /robot/robotnik_base_control/cmd_vel_timeout: 0.25
 * /robot/robotnik_base_control/enable_odom_tf: True
 * /robot/robotnik_base_control/left_wheel: ['robot_front_lef...
 * /robot/robotnik_base_control/linear/x/has_acceleration_limits: True
 * /robot/robotnik_base_control/linear/x/has_velocity_limits: True
 * /robot/robotnik_base_control/linear/x/max_acceleration: 6.0
 * /robot/robotnik_base_control/linear/x/max_velocity: 3.0
 * /robot/robotnik_base_control/linear/x/min_acceleration: -6.0
 * /robot/robotnik_base_control/linear/x/min_velocity: -3.0
 * /robot/robotnik_base_control/odom_frame_id: robot_odom
 * /robot/robotnik_base_control/pose_covariance_diagonal: [0.001, 0.001, 10...
 * /robot/robotnik_base_control/publish_rate: 50.0
 * /robot/robotnik_base_control/right_wheel: ['robot_front_rig...
 * /robot/robotnik_base_control/twist_covariance_diagonal: [0.001, 0.001, 10...
 * /robot/robotnik_base_control/type: diff_drive_contro...
 * /robot/robotnik_base_control/wheel_radius: 0.11
 * /robot/robotnik_base_control/wheel_radius_multiplier: 1.0
 * /robot/robotnik_base_control/wheel_separation: 0.47
 * /robot/robotnik_base_control/wheel_separation_multiplier: 1.0
 * /robot/twist_mux/locks: [{'topic': 'robot...
 * /robot/twist_mux/topics: [{'topic': 'pad_t...
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    rviz (rviz/rviz)
  /robot/
    controller_spawner (controller_manager/spawner)
    controller_spawner_arm (controller_manager/spawner)
    controller_spawner_gripper (controller_manager/spawner)
    robot_state_publisher (robot_state_publisher/state_publisher)
    twist_marker (twist_mux/twist_marker)
    twist_mux (twist_mux/twist_mux)
    urdf_spawner_robot_model (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [9915]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 206a3028-7092-11eb-9b13-080027d86f22
process[rosout-1]: started with pid [9936]
started core service [/rosout]
process[gazebo-2]: started with pid [9943]
process[gazebo_gui-3]: started with pid [9948]
process[robot/urdf_spawner_robot_model-4]: started with pid [9953]
process[robot/robot_state_publisher-5]: started with pid [9954]
process[robot/controller_spawner-6]: started with pid [9955]
process[robot/twist_mux-7]: started with pid [9956]
process[robot/twist_marker-8]: started with pid [9965]
process[robot/controller_spawner_arm-9]: started with pid [9971]
process[robot/controller_spawner_gripper-10]: started with pid [9972]
process[rviz-11]: started with pid [9976]
[ WARN] [1613505849.438341989]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[ERROR] [1613505849.450205751]: No link elements found in urdf file
[INFO] [1613505849.654991, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1613505849.662994, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[robot/robot_state_publisher-5] process has died [pid 9954, exit code 1, cmd /opt/ros/melodic/lib/robot_state_publisher/state_publisher /joint_states:=joint_states __name:=robot_state_publisher __log:=/home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-robot_state_publisher-5.log].
log file: /home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-robot_state_publisher-5*.log
[INFO] [1613505849.719012, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ERROR] [1613505849.816743305]: No link elements found in urdf file
[ERROR] [1613505849.891885886]: PluginlibFactory: The plugin for class 'teleop_panel/Teleop' failed to load.  Error: According to the loaded plugin descriptions the class teleop_panel/Teleop with base class type rviz::Panel does not exist. Declared types are  rviz_plugin_tutorials/Teleop
[rospack] Error: no package given
[librospack]: error while executing command
[rospack] Error: no package given
[librospack]: error while executing command
[INFO] [1613505849.935825, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1613505849.937485, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1613505849.965565347]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1613505849.967025054]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1613505850.005230578]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1613505850.006210368]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1613505850.218991736]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1613505850.237434368]: Physics dynamic reconfigure ready.
[INFO] [1613505850.239623, 0.000000]: Calling service /gazebo/spawn_urdf_model
Error:   No link elements found in urdf file
         at line 179 in /build/urdfdom-YMMa9X/urdfdom-1.0.0/urdf_parser/src/model.cpp
Error [parser_urdf.cc:3166] Unable to call parseURDF on robot model
Error [parser.cc:406] parse as old deprecated model file failed.
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[ERROR] [1613505850.817318808, 0.466000000]: No link elements found in urdf file
[INFO] [1613505860.366432, 10.001000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name robot
[ERROR] [1613505860.367320, 10.003000]: Spawn service failed. Exiting.
[robot/urdf_spawner_robot_model-4] process has died [pid 9953, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -x 0 -y 0 -z 0 -urdf -param robot_description -model robot __name:=urdf_spawner_robot_model __log:=/home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-urdf_spawner_robot_model-4.log].
log file: /home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-urdf_spawner_robot_model-4*.log
[WARN] [1613505879.764718, 29.368000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1613505879.767505, 29.371000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1613505879.836663, 29.439000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[robot/controller_spawner_arm-9] process has finished cleanly
log file: /home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-controller_spawner_arm-9*.log
[robot/controller_spawner_gripper-10] process has finished cleanly
log file: /home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-controller_spawner_gripper-10*.log
[robot/controller_spawner-6] process has finished cleanly
log file: /home/au/.ros/log/206a3028-7092-11eb-9b13-080027d86f22/robot-controller_spawner-6*.log

`
what do you think I should do?

**Comment by alex-arnal** [comment]
Maybe you can try running rosdep install from your workspace directory to resolve missing dependencies. It seems that there are some problems loading the URDF of the robot, maybe caused by missing dependencies.

```
rosdep install --from-path src --ignore-src -r -y
```

This warning is not important but you can solve it updating state_publisher to robot_state_publisher in [rbkairos_common/rbkairos_description/launch/rbkairos_state_robot.launch](https://github.com/RobotnikAutomation/rbkairos_common/blob/kinetic-devel/rbkairos_description/launch/rbkairos_state_robot.launch)
> [ WARN] [1613505849.438341989]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead

No idea :s

> [ERROR] [1613505849.450205751]: No link elements found in urdf file


This is probably caused if you have some ros control plugins missing. 

> [INFO] [1613505849.654991, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [INFO] [1613505849.662994, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller

To discard this, I recomend to install:

```bash
sudo apt-get install ros-melodic-control*
```
and Gazebo stuff

```bash
sudo apt-get install ros-melodic-gazebo-*
```

I have tried the simulation (this time in Melodic, Ubuntu 18.05 and Gazebo 9.16.0) with the same packages as I did it in Kinetic and Ubuntu 16.04 and it is working for me. I hope this solve your issues.

Álex

**Comment by armulrich** [comment]
That didn't do the trick, but I managed to do it after switching my rbkairos_common from melodic devel to kinetic devel and rebuilding.  Now I only have the pid gain errors, that I will ignore.

So thankyou very much for getting me on the right track.

 I am however now experiencing issues with making a ros navigation package (with maps)  for the rbkairos, which is why I wanted to ask if there is a prebuilt package for navigation with the rbkairos sim, that you have available for use.

**Comment by alex-arnal** [comment]
Yes, you have some configurations available to work with ROS navigation in [summit_xl_common/summit_xl_navigation](https://github.com/RobotnikAutomation/summit_xl_common/tree/kinetic-devel/summit_xl_navigation). Keep in mind that the mobile base of the RB-Kairos is a Summit XL Steel, so you can use this package to perform navigation.

**Comment by armulrich** [comment]
Great.
